version: "3"
env:
  PGM_NAME: yp
tasks:
  build:
    cmds:
      - cargo fmt
      - cargo build --release
  run:
    deps: [build]
    cmds:
      - target/release/$PGM_NAME
  install:
    deps: [build]
    cmds:
      - cp target/release/$PGM_NAME ~/bin