version: "3"
env:
  PGM_NAME: yp
tasks:
  build:
    cmds:
      - cargo fmt
      - cargo build --release
  run:
    deps: [build]
    cmds:
      - target/release/$PGM_NAME
  install:
    deps: [build]
    cmds:
      - cp target/release/$PGM_NAME ~/bin
  loc:
    desc: Count lines of code
    cmds:
      - tokei
  loc:files:
    desc: Lines of code per source file
    cmds:
      - tokei src/ --files

  version:patch:
    desc: Bump patch version (0.0.x)
    vars:
      CURRENT:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/'
      MAJOR:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/' | cut -d. -f1
      MINOR:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/' | cut -d. -f2
      PATCH:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/' | cut -d. -f3
    cmds:
      - |
        NEW="{{.MAJOR}}.{{.MINOR}}.$(({{.PATCH}} + 1))"
        sed -i "s/^version = \"{{.CURRENT}}\"/version = \"$NEW\"/" Cargo.toml
        cargo generate-lockfile
        echo "Bumped {{.CURRENT}} → $NEW"

  version:minor:
    desc: Bump minor version (0.x.0)
    vars:
      CURRENT:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/'
      MAJOR:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/' | cut -d. -f1
      MINOR:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/' | cut -d. -f2
    cmds:
      - |
        NEW="{{.MAJOR}}.$(({{.MINOR}} + 1)).0"
        sed -i "s/^version = \"{{.CURRENT}}\"/version = \"$NEW\"/" Cargo.toml
        cargo generate-lockfile
        echo "Bumped {{.CURRENT}} → $NEW"

  version:major:
    desc: Bump major version (x.0.0)
    vars:
      CURRENT:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/'
      MAJOR:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/' | cut -d. -f1
    cmds:
      - |
        NEW="$(({{.MAJOR}} + 1)).0.0"
        sed -i "s/^version = \"{{.CURRENT}}\"/version = \"$NEW\"/" Cargo.toml
        cargo generate-lockfile
        echo "Bumped {{.CURRENT}} → $NEW"

  version:tag:
    desc: Create git tag from current version
    vars:
      VERSION:
        sh: grep '^version' Cargo.toml | head -1 | sed 's/.*"\(.*\)"/\1/'
    cmds:
      - git tag -a "v{{.VERSION}}" -m "v{{.VERSION}}"
      - echo "Tagged v{{.VERSION}}"